### ISSUE TITLE
Release version for latest master commit

### ISSUE THREAD

**Issue by leoc1990** [vbanthia/rspec_html_reporter#14]
Hi, I am wondering if you could release a version (can be patch release) for https://github.com/vbanthia/rspec_html_reporter/commit/124be31d101efffd46ed1f703011fac7696e0bab. 

I am running into the Multiple Exception Error that that commit fixes, and it would be nice to be able to pull it as a stable version from the gem.

Thanks!

**Comment by vbanthia** [comment]
release v1.0.3
https://github.com/vbanthia/rspec_html_reporter/releases/tag/v1.0.3
